/**
 * Route paths — one source of truth for every URL in the site.
 *
 * These MUST stay aligned with `src/seo/siteMetadata.js`, which drives the
 * static HTML pages, sitemap and JSON-LD generated by `scripts/postbuild.mjs`.
 * A route that exists here but not there will 404 on a hard refresh in
 * production, because GitHub Pages serves real files, not an SPA fallback.
 *
 * Planned routes are listed but commented until their page exists, so this file
 * documents the roadmap without pretending the routes are live.
 */

export const ROUTES = {
    home: "/",
    privacy: "/privacy/",
    terms: "/terms/",

    /* Planned — uncomment alongside the page AND its siteMetadata entry.
    calculator: "/calculator/",
    work:       "/work/",
    workItem:   "/work/:slug/",
    blog:       "/blog/",
    blogPost:   "/blog/:slug/",
    */
} as const;

export type RouteKey = keyof typeof ROUTES;
export type RoutePath = (typeof ROUTES)[RouteKey];

/** Section anchors on the home page, used by the header nav. */
export const HOME_SECTIONS = {
    packages: "packages",
    stages: "stages",
    faq: "faq",
    contact: "contact",
} as const;

export type HomeSectionId = (typeof HOME_SECTIONS)[keyof typeof HOME_SECTIONS];
