import { SERVICE_OFFERINGS } from "../../data/services.js";

const ESTIMATOR_WEBSITE_PRICING = {
    landing: {
        basePrice: 600,
        includedPages: 1,
        summaryFeatures: [
            "1 main page included",
            "Custom responsive design",
            "SEO & analytics setup",
            "Domain & launch setup",
        ],
        includedFeatures: [
            "Custom one-page website (Legal pages included at no extra cost)",
            "Responsive design for all devices",
            "Contact or enquiry form",
            "Basic SEO setup",
            "Google Analytics setup",
            "SSL certificate & HTTPS security",
            "Google Search Console setup",
            "Social media integration",
            "Google Maps integration, if needed",
            "Smooth animations & interactions",
            "Cookie banner setup",
            "Performance optimisation",
            "Browser and device testing",
            "Domain & hosting connection",
            "Website launch",
            "Post-launch support",
        ],
    },
    business: {
        basePrice: 900,
        includedPages: 4,
        summaryFeatures: [
            "Up to 4 main pages included",
            "Custom responsive design",
            "SEO & analytics setup",
            "Domain & launch setup",
        ],
        includedFeatures: [
            "Up to 4 main pages (Legal pages included at no extra cost)",
            "Responsive design for all devices",
            "Contact or enquiry form",
            "Website navigation",
            "Basic SEO setup",
            "Google Analytics setup",
            "SSL certificate & HTTPS security",
            "Google Search Console setup",
            "Social media integration",
            "Google Maps integration, if needed",
            "Smooth animations & interactions",
            "Cookie banner setup",
            "Performance optimisation",
            "Browser and device testing",
            "Domain & hosting connection",
            "Website launch",
            "Post-launch support",
        ],
    },
    catalogue: {
        basePrice: 1700,
        includedPages: 5,
        hasProductTemplate: true,
        summaryFeatures: [
            "Up to 5 main pages included",
            "Custom responsive design",
            "Catalogue setup",
            "SEO & analytics setup",
        ],
        includedFeatures: [
            "Up to 5 main pages (Legal pages included at no extra cost)",
            "Responsive design for all devices",
            "Reusable product/service pages",
            "Categories and basic filters",
            "Catalogue search",
            "Content management system (update your products anytime)",
            "Contact or enquiry form",
            "Basic SEO setup",
            "Google Analytics setup",
            "SSL certificate & HTTPS security",
            "Google Search Console setup",
            "Social media integration",
            "Google Maps integration, if needed",
            "Smooth animations & interactions",
            "Cookie banner setup",
            "Performance optimisation",
            "Browser and device testing",
            "Domain & hosting connection",
            "Website launch",
            "Post-launch support",
        ],
    },
    ecommerce: {
        basePrice: 2500,
        includedPages: 5,
        hasProductTemplate: true,
        summaryFeatures: [
            "Up to 5 main pages included",
            "Custom responsive design",
            "E-commerce setup",
            "SEO & analytics setup",
        ],
        includedFeatures: [
            "Up to 5 main pages (Legal pages included at no extra cost)",
            "Custom responsive e-commerce design",
            "Reusable product/service pages",
            "Categories and basic filters",
            "Catalogue search",
            "Shopping cart",
            "Secure checkout",
            "Payment integration",
            "Basic delivery and shipping setup",
            "Order management",
            "Content management system (update your products anytime)",
            "Stock / inventory management",
            "Product variations (size, colour, etc.)",
            "Contact or enquiry form",
            "Basic SEO setup",
            "Google Analytics setup",
            "SSL certificate & HTTPS security",
            "Google Search Console setup",
            "Social media integration",
            "Google Maps integration, if needed",
            "Smooth animations & interactions",
            "Cookie banner setup",
            "Performance optimisation",
            "Browser and device testing",
            "Domain & hosting connection",
            "Website launch",
            "Post-launch support",
        ],
    },
};

const websiteTypes = SERVICE_OFFERINGS.flatMap((service) => {
    const id = service.estimatorWebsiteTypeId;
    const pricing = id ? ESTIMATOR_WEBSITE_PRICING[id] : undefined;

    if (pricing) {
        return [{ id, label: service.label, description: service.description, ...pricing }];
    }

    return id === "web-application"
        ? [{
            id,
            label: service.label,
            description: service.description,
            directContact: true,
            possibleFeatures: [
                "User accounts & secure login",
                "Customer/client dashboards",
                "Admin dashboard",
                "Different user roles & permissions",
                "Custom forms & workflows",
                "Booking & scheduling systems",
                "Online payments",
                "Search & advanced filtering",
                "Email notifications",
                "Content management",
                "File uploads & document management",
                "Third-party integrations",
                "API integrations",
                "Automated processes",
                "Custom business tools",
                "Analytics & reporting",
                "Responsive design",
                "Security & performance optimisation",
                "Deployment & launch support",
            ],
        }]
        : [];
});

export const pricingConfig = {
    websiteTypes,
    pageRange: { minimum: 1, maximum: 20 },
    extraPagePrice: 150,
    extraPageLabel: "Additional core page",
    productPagesNote: "Products share one page template, so they don’t count as separate pages.",
    features: [
        { id: "custom-section", label: "Additional custom section", description: "One additional custom-designed content block or section.", price: 80, appliesTo: ["landing", "business", "catalogue", "ecommerce"], recommendedFor: [] },
        { id: "cms", label: "CMS / Editable Content", description: "One editable content area or collection with basic admin functionality.", price: 600, appliesTo: ["landing", "business", "ecommerce"], recommendedFor: [] },
        { id: "advanced-forms", label: "Advanced Forms", description: "Complex enquiries, file uploads or conditional fields.", price: 300, appliesTo: ["landing", "business", "catalogue", "ecommerce"], recommendedFor: [] },
        { id: "booking", label: "Booking / Appointments", description: "Let visitors book services or appointments.", price: 450, appliesTo: ["landing", "business", "catalogue"], recommendedFor: [] },
        { id: "advanced-filters", label: "Advanced Product Filters", description: "Filter by multiple attributes, price ranges or custom product data.", price: 400, appliesTo: ["catalogue", "ecommerce"], recommendedFor: [] },
        { id: "advanced-shipping", label: "Advanced Delivery & Shipping Rules", description: "Set delivery zones, rates or rules beyond the included basic setup.", price: 350, appliesTo: ["ecommerce"], recommendedFor: [] },
        { id: "discounts", label: "Discounts & Promo Codes", description: "Create promotional codes and discounts.", price: 350, appliesTo: ["ecommerce"], recommendedFor: [] },
        { id: "customer-accounts", label: "Customer Accounts", description: "Registration, login, password reset, profiles, saved details and order history.", price: 1000, appliesTo: ["ecommerce"], recommendedFor: [] },
        { id: "stock", label: "Stock Management", description: "Track quantities, availability, low-stock status and prevent orders for unavailable products.", price: 450, appliesTo: ["ecommerce"], recommendedFor: [] },
        { id: "multilingual", label: "Multilingual Support", description: "Provide the website in one additional language.", price: 400, appliesTo: ["landing", "business", "catalogue", "ecommerce"], recommendedFor: [] },
        { id: "integrations", label: "Third-Party Integration", description: "Connect a CRM, email marketing, analytics, booking, delivery, accounting or other external service.", price: 300, appliesTo: ["landing", "business", "catalogue", "ecommerce"], recommendedFor: [] },
        { id: "product-uploads", label: "Additional Product Uploads", description: "Additional catalogue population beyond the agreed launch scope.", price: null, appliesTo: ["catalogue", "ecommerce"], recommendedFor: [] },
        { id: "content-photography", label: "Copywriting & Photography", description: "Professional copywriting and product photography for your website.", price: null, appliesTo: ["landing", "business", "catalogue", "ecommerce"], recommendedFor: [] },
    ],
    startingPoints: [
        { id: "design-development", label: "I need design + development", description: "The complete website needs to be designed and developed.", multiplier: 1 },
        { id: "finished-design", label: "I already have a finished design", description: "The website design is ready and mainly needs development.", multiplier: 0.85 },
        { id: "existing-website", label: "I have an existing website", description: "The current website needs redesigning or rebuilding.", multiplier: 1.1 },
    ],
    estimateRange: { minimumMultiplier: 0.9, maximumMultiplier: 1.1, rounding: 50 },
};

export const initialEstimatorAnswers = {
    websiteTypeId: "",
    pageCount: 1,
    featureIds: [],
    startingPointId: "",
};
