import { SERVICE_OFFERINGS } from "../../data/services.js";

const ESTIMATOR_WEBSITE_PRICING = {
    landing: {
        basePrice: 600,
        includedPages: 1,
        summaryFeatures: [
            "1 main page included",
            "Custom responsive design",
            "SEO & analytics setup",
            "Domain & launch setup",
        ],
        includedFeatures: [
            "Custom one-page website (Legal pages included at no extra cost)",
            "Responsive design for all devices",
            "Contact or enquiry form",
            "Basic SEO setup",
            "Google Analytics setup",
            "SSL certificate & HTTPS security",
            "Google Search Console setup",
            "Social media integration",
            "Google Maps integration, if needed",
            "Smooth animations & interactions",
            "Cookie banner setup",
            "Performance optimisation",
            "Browser and device testing",
            "Domain & hosting connection",
            "Website launch",
            "Post-launch support",
        ],
    },
    business: {
        basePrice: 900,
        includedPages: 4,
        summaryFeatures: [
            "Up to 4 main pages included",
            "Custom responsive design",
            "SEO & analytics setup",
            "Domain & launch setup",
        ],
        includedFeatures: [
            "Up to 4 main pages (Legal pages included at no extra cost)",
            "Responsive design for all devices",
            "Contact or enquiry form",
            "Website navigation",
            "Basic SEO setup",
            "Google Analytics setup",
            "SSL certificate & HTTPS security",
            "Google Search Console setup",
            "Social media integration",
            "Google Maps integration, if needed",
            "Smooth animations & interactions",
            "Cookie banner setup",
            "Performance optimisation",
            "Browser and device testing",
            "Domain & hosting connection",
            "Website launch",
            "Post-launch support",
        ],
    },
    catalogue: {
        basePrice: 1700,
        includedPages: 5,
        hasProductTemplate: true,
        summaryFeatures: [
            "Up to 5 main pages included",
            "Custom responsive design",
            "Catalogue setup",
            "SEO & analytics setup",
        ],
        includedFeatures: [
            "Up to 5 main pages (Legal pages included at no extra cost)",
            "Responsive design for all devices",
            "Reusable product/service pages",
            "Categories and basic filters",
            "Catalogue search",
            "Content management system (update your products anytime)",
            "Contact or enquiry form",
            "Basic SEO setup",
            "Google Analytics setup",
            "SSL certificate & HTTPS security",
            "Google Search Console setup",
            "Social media integration",
            "Google Maps integration, if needed",
            "Smooth animations & interactions",
            "Cookie banner setup",
            "Performance optimisation",
            "Browser and device testing",
            "Domain & hosting connection",
            "Website launch",
            "Post-launch support",
        ],
    },
    ecommerce: {
        basePrice: 2500,
        includedPages: 5,
        hasProductTemplate: true,
        summaryFeatures: [
            "Up to 5 main pages included",
            "Custom responsive design",
            "E-commerce setup",
            "SEO & analytics setup",
        ],
        includedFeatures: [
            "Up to 5 main pages (Legal pages included at no extra cost)",
            "Custom responsive e-commerce design",
            "Reusable product/service pages",
            "Categories and basic filters",
            "Catalogue search",
            "Shopping cart",
            "Secure checkout",
            "Payment integration",
            "Basic delivery and shipping setup",
            "Order management",
            "Content management system (update your products anytime)",
            "Stock / inventory management",
            "Product variations (size, colour, etc.)",
            "Contact or enquiry form",
            "Basic SEO setup",
            "Google Analytics setup",
            "SSL certificate & HTTPS security",
            "Google Search Console setup",
            "Social media integration",
            "Google Maps integration, if needed",
            "Smooth animations & interactions",
            "Cookie banner setup",
            "Performance optimisation",
            "Browser and device testing",
            "Domain & hosting connection",
            "Website launch",
            "Post-launch support",
        ],
    },
};

const websiteTypes = SERVICE_OFFERINGS.flatMap((service) => {
    const id = service.estimatorWebsiteTypeId;
    const pricing = id ? ESTIMATOR_WEBSITE_PRICING[id] : undefined;

    if (pricing) {
        return [{ id, label: service.label, description: service.description, ...pricing }];
    }

    return id === "web-application"
        ? [{
            id,
            label: service.label,
            description: service.description,
            directContact: true,
            possibleFeatures: [
                "User accounts & secure login",
                "Customer/client dashboards",
                "Admin dashboard",
                "Different user roles & permissions",
                "Custom forms & workflows",
                "Booking & scheduling systems",
                "Online payments",
                "Search & advanced filtering",
                "Email notifications",
                "Content management",
                "File uploads & document management",
                "Third-party integrations",
                "API integrations",
                "Automated processes",
                "Custom business tools",
                "Analytics & reporting",
                "Responsive design",
                "Security & performance optimisation",
                "Deployment & launch support",
            ],
        }]
        : [];
});

export const pricingConfig = {
    websiteTypes,
    pageRange: { minimum: 1, maximum: 20 },
    extraPagePrice: 150,
    extraPageLabel: "Additional core page",
    productPagesNote: "Products share one page template, so they don’t count as separate pages.",
    features: [
        { id: "cms-landing", label: "Admin Panel / Content Management", description: "Manage selected website content yourself through an easy-to-use admin area, including 4 custom blocks.", price: 300, appliesTo: ["landing"], recommendedFor: [] },
        { id: "cms-business", label: "Admin Panel / Content Management", description: "Manage selected website content yourself through an easy-to-use admin area, including 8 custom blocks.", price: 600, appliesTo: ["business"], recommendedFor: [] },
        { id: "booking-integration", label: "Booking Integration", description: "Connect an existing external booking service to your website.", price: 100, appliesTo: ["landing", "business", "catalogue", "ecommerce"], recommendedFor: [] },
        { id: "custom-booking", label: "Custom Booking System", description: "Custom appointment booking with availability, confirmations and admin management.", price: 300, appliesTo: ["landing", "business", "catalogue", "ecommerce"], recommendedFor: [] },
        { id: "payments-landing", label: "Online Payments / Deposits", description: "Accept online payments or deposits directly through the website.", price: 350, appliesTo: ["landing"], recommendedFor: [] },
        { id: "payments-business", label: "Online Payments / Deposits", description: "Accept online payments or deposits through the website.", price: 250, appliesTo: ["business"], recommendedFor: [] },
        { id: "multilingual", label: "Multilingual Support", description: "Add one additional language to your website.", price: 100, appliesTo: ["landing", "business", "catalogue", "ecommerce"], recommendedFor: [] },
        { id: "advanced-animations-landing", label: "Advanced Animations", description: "Add custom animations and interactive effects beyond the standard website animations.", price: 200, appliesTo: ["landing"], recommendedFor: [] },
        { id: "advanced-animations", label: "Advanced Animations", description: "Add custom animations and interactive effects beyond the standard website animations.", price: 250, appliesTo: ["business", "catalogue", "ecommerce"], recommendedFor: [] },
        { id: "advanced-filters", label: "Advanced Filters", description: "Add more detailed filtering by categories, attributes or other criteria.", price: 100, appliesTo: ["catalogue", "ecommerce"], recommendedFor: [] },
        { id: "advanced-search", label: "Advanced Search", description: "Add enhanced search functionality for a larger catalogue.", price: 100, appliesTo: ["catalogue", "ecommerce"], recommendedFor: [] },
        { id: "integrations", label: "Third-Party Integration", description: "Connect your catalogue to a CRM, inventory system or another external service.", price: 200, appliesTo: ["catalogue", "ecommerce"], recommendedFor: [] },
        { id: "discounts", label: "Discounts & Promo Codes", description: "Add configurable discount codes and promotional offers.", price: 300, appliesTo: ["ecommerce"], recommendedFor: [] },
        { id: "wishlist", label: "Wishlist", description: "Let customers save products to view or purchase later.", price: 200, appliesTo: ["ecommerce"], recommendedFor: [] },
        { id: "product-comparison", label: "Product Comparison", description: "Let customers compare selected products and their key features side by side.", price: 150, appliesTo: ["ecommerce"], recommendedFor: [] },
        { id: "customer-accounts", label: "Customer Accounts", description: "Let customers create accounts, manage details and view their orders.", price: 1500, appliesTo: ["ecommerce"], recommendedFor: [] },
        { id: "advanced-shipping", label: "Advanced Shipping Setup", description: "Add multiple shipping methods, zones or conditional delivery rules.", price: 150, appliesTo: ["ecommerce"], recommendedFor: [] },
        { id: "product-reviews", label: "Product Reviews", description: "Product reviews when they are not included in the base package.", price: 450, appliesTo: ["ecommerce"], recommendedFor: [] },
    ],
    startingPoints: [
        { id: "design-development", label: "I need design + development", description: "The complete website needs to be designed and developed.", multiplier: 1 },
        { id: "finished-design", label: "I already have a finished design", description: "The website design is ready and mainly needs development.", multiplier: 0.85, priceAdjustments: { landing: -200, business: -350, catalogue: -400, ecommerce: -400 }, priceLabels: { landing: "-£200", business: "-£350", catalogue: "-£400", ecommerce: "-£400" } },
    ],
    estimateRange: { minimumMultiplier: 0.9, maximumMultiplier: 1.1, rounding: 50 },
};

export const initialEstimatorAnswers = {
    websiteTypeId: "",
    pageCount: 1,
    featureIds: [],
    startingPointId: "design-development",
};
